version: 2
jobs:
  build:
    # directory where steps will run
    working_directory: ~/treasure-data/digdag
    parallelism: 4
    shell: /bin/bash --login

    # environment Variables in a Job https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-job
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      TERM: dumb
      BUILD_IMAGE: digdag/digdag-build:20170228T062524-309738ae71c4642d72e2978568fea14a84d0f2a9

    # executor type https://circleci.com/docs/2.0/executor-types/
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init

    steps:
    # Checks out the code to the working directory
    - checkout
    - run:
        command: 'mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS'
    - run:
        command: 'echo ''UTC'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure
          -f noninteractive tzdata; sudo service mysql restart; sudo service postgresql
          restart; '
    - run:
        command: 'sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0/bin/java; sudo update-alternatives --set javac /usr/lib/jvm/jdk1.8.0/bin/javac; echo -e "export JAVA_HOME=/usr/lib/jvm/jdk1.8.0" >> $BASH_ENV'
    - run:
        command: 'sudo docker info >/dev/null 2>&1 || sudo service docker start; '
    # Restore the dependency cache
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
        - v1-dep-
    - run: |
        docker run \
        -w /digdag \
        -v `pwd`/:/digdag \
        -v ~/.gradle:/root/.gradle \
        $BUILD_IMAGE \
        ./gradlew testClasses
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/docker
        - ~/.gradle
        - ~/.m2
    # Test
    - run: CI_NODE_TOTAL=$CIRCLE_NODE_TOTAL CI_NODE_INDEX=$CIRCLE_NODE_INDEX ci/run_td_tests.sh
    - run: ci/circle_gather_test_reports.sh
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

  deploy_docs:
    # directory where steps will run
    working_directory: ~/treasure-data/digdag
    shell: /bin/bash --login

    environment:
      TERM: dumb
      BUILD_IMAGE: digdag/digdag-build:20170228T062524-309738ae71c4642d72e2978568fea14a84d0f2a9

    # executor type https://circleci.com/docs/2.0/executor-types/
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init

    steps:
    # Checks out the code to the working directory
    - checkout
    - run: ci/run_deployment.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_docs:
          filters:
            branches:
              only:
                - master